# Generated by Django 4.2.3 on 2023-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_number',
            field=models.IntegerField(null=True),
        ),
    ]
