# Generated by Django 4.2.3 on 2023-07-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_student_std_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelowner'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_owner_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='lease',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='power_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='security_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='sop_status',
            field=models.CharField(default='Available', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('M', 'Mixed'), ('S', 'Single')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='water_status',
            field=models.CharField(choices=[('tap', 'National Water'), ('Tanks', 'Only Tanks'), ('all', 'National water & Tanks')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hostelowner',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostelowner',
            name='hostel_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hostelowner',
            name='landlord_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
