# Generated by Django 4.2.3 on 2023-07-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_hostel_location_hostel_hostel_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='Location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostelowner'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_owner_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='lease',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='power_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='security_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='sop_status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('M', 'Mixed'), ('S', 'Single')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='total_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='water_status',
            field=models.CharField(choices=[('tap', 'National Water'), ('Tanks', 'Only Tanks'), ('all', 'National water & Tanks')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostelowner',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hostelowner',
            name='hostel_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hostelowner',
            name='landlord_name',
            field=models.CharField(max_length=30),
        ),
    ]
