# Generated by Django 4.2.3 on 2023-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_hostel_location_alter_hostel_hostel_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelOwnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Hostel_Name', models.CharField(max_length=30)),
                ('Total_Number_of_Rooms', models.IntegerField()),
            ],
        ),
    ]
