# Generated by Django 4.2.3 on 2023-07-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_hostelownerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
