# Generated by Django 4.2.3 on 2023-07-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
