# Generated by Django 4.2.3 on 2023-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_alter_hostel_hostel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
