# Generated by Django 4.2.3 on 2023-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_alter_hostel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('Mixed', 'Mixed'), ('Single', 'Single')], max_length=100),
        ),
    ]
