# Generated by Django 4.2.3 on 2023-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_hostel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='water_status',
            field=models.CharField(choices=[('Tap Water', 'National Water'), ('Tanks', 'Only Tanks'), ('all', 'National water & Tanks')], max_length=10),
        ),
    ]
