# Generated by Django 4.2.3 on 2023-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_alter_hostel_water_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='active_contact',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
