# Generated by Django 4.2.3 on 2023-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_booking_active_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
