# Generated by Django 4.2.3 on 2023-07-17 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0016_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='active_contact',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
