# Generated by Django 4.2.3 on 2023-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_alter_booking_active_contact_alter_booking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='FirstName',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
