# Generated by Django 4.2.3 on 2023-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_remove_booking_user_booking_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='FirstName',
            field=models.CharField(max_length=10),
        ),
    ]
